name: CI

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: ${{ steps.buildozer.outputs.filename }}
